export * from './home';
export * from './login';
export * from './register';
export * from './logout';
export * from './movie-card';
export * from './movies';
export * from './nav';
export * from './add-movie';
export * from './details';
export * from './edit-movie'